### ISSUE TITLE
Cannot find this in the install packages section of Atom

### ISSUE THREAD

**Issue by cscalfani** [jmitchell/atom-language-dhall#2]
Is this no longer supported? If not, what is?

**Comment by jmitchell** [comment]
Thanks for your interest. This was never released on https://atom.io/packages because the underlying parser has some [problematic bugs](https://github.com/jmitchell/tree-sitter-dhall/issues). The Dhall grammar is still evolving, and I am not actively working on this tree-sitter approach anymore. I've added "buggy and not released" to this repo's description.

You're welcome to try loading the package from a local clone, but be forewarned some expressions simply won't parse.

Now there's [language server support](https://github.com/dhall-lang/dhall-haskell/pull/843) in the Haskell implementation of Dhall, and apparently a [Visual Studio (Code) plugin](https://marketplace.visualstudio.com/items?itemName=panaeon.vscode-dhall-lsp-server) that uses it. They seem promising, but I haven't personally used them yet.
